### ISSUE TITLE
A question about this IOT client and the M2Mqtt

### ISSUE THREAD

**Issue by stefan2410** [ppatierno/pi2toeventhubs#1]
Hi, I am new to MQTT and I would appreciate some help.
I build  a windows service application  using a  Microsoft VoIP SDK which is entirely asynchronous-parallelism (using TPL) and with a heavy workload.  I want our application to communicate as an MQTT client, with an external system - (RabbitMQ 0.9.1 broker with an MQTT plugin). I am afraid to use M2Mqtt because it is using internal threads and if there is any problem maybe to influence the main functionality. 
As I have seen here the IOT Client is using the TPL , so all threads will be controlled from the TPL Task Scheduler.  I think it is more safe to use it  instead of the M2Mqtt.
My question is if it is complete comparing to M2Mqtt,  if I need a special handling for the RabbitMQ as I will not use the AMQP .Net Lite and about the SSL/TLS feature for the client (listening in port 8883).
thank you 
Stefan

**Comment by clamaz** [comment]
Hello,

I'm trying to use your library M2MqttAutoReconnect V. 4.4.0.1
But I can't understand how to use reconnection.

Where to find an example?

Thank you
